# Generated by Django 5.0.2 on 2024-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_nucleo_rename_institutions_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleo',
            name='short',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
