# Generated by Django 5.0.2 on 2024-04-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nucleo_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleo',
            name='institution',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.institution'),
            preserve_default=False,
        ),
    ]
